apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysampleapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myappcontainer
        image: akumarvinay/new-application:$BUILD_NUMBER
        ports:
        - containerPort: 8080  
        
